# Generated by Django 5.2.8 on 2025-11-25 09:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('branch', models.CharField(blank=True, max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('intime', models.TimeField(blank=True, null=True)),
                ('outtime', models.TimeField(blank=True, null=True)),
                ('in_image', models.ImageField(blank=True, null=True, upload_to='attendance/in/')),
                ('out_image', models.ImageField(blank=True, null=True, upload_to='attendance/out/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
