# Generated by Django 5.2.9 on 2026-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_identifier',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='attendance',
            name='no_of_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='remark',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
